### ISSUE TITLE
Release 1.0.3

### ISSUE THREAD

**Issue by tferr** [jzy3d/jzy3d-api#102]
@martin-pernollet
Would it be possibe to release version 1.0.3? We [are using](https://github.com/fiji/Simple_Neurite_Tracer/blob/scijava/src/main/java/sc/fiji/snt/viewer/Viewer3D.java) some of the fixes in the current snapshot, and our code no longer compiles with 1.02. For us, snapshot dependencies are problematic because they do not [allow automated builds](https://imagej.net/Architecture#How_SciJava_achieves_reproducible_builds). Even if 1.0.3 is not released to [Maven](https://mvnrepository.com/artifact/org.jzy3d/jzy3d-api), we could still use [jitpack](https://jitpack.io/#jzy3d/jzy3d-api).

Also, Let me thank you for this wonderful work: we were able to build a dedicated viewer to visualize neuronal reconstructions (snapshot [here](https://imagej.net/SNT)), solely based on jzy3d. The API was intuitive, and the examples really useful. Thank you so much for your work!

**Comment by martinpernollet** [comment]
Sorry, for the moment I am quite busy and not able to make the release
soon. I'll do my best, but for now I can't :(

Thank you for your kind words and for sharing links about your usage of
Jzy3d, I am always glad to read about it!




Le mar. 28 mai 2019 à 13:36, Tiago Ferreira <notifications@github.com> a
écrit :

**Comment by jzy3d** [comment]
Hi Tiago, better late than never : [1.0.3](https://github.com/jzy3d/jzy3d-api/tree/1.0.3) is now available as release version on jzy3d maven repository + git branch. 

I am preparing version 2.0.0-SNAPSHOT that will soon arrive on master branch. It will improve compatibility of {JVM,OS,GPU} by providing an alternate renderer based on CPU only.

**Comment by tferr** [comment]
This is awesome!! thanks a lot! 2.0 sounds awesome! on my laptop without discrete graphics card (intel built-in HD) jzy3D can easily become a resource hog. I am really eager to try it out! Thanks for continuing working on jzy3d!

**Comment by jzy3d** [comment]
You may have a more quiet jzy3d by calling `chart.setAnimated(false); ` 
By default chart are animated and use a thread that is by default trying to run as fast as possible. This is why the chart may bump your CPU usage. This is not fixed with 2.0 on native (jogl) charts but you may create an enhancement query ticket if I did not misunderstood your problem. 
The emulated GL charts coming with 2.0 do not cause this problem since the animation thread is making long pauses.

**Comment by jzy3d** [comment]
Better CPU usage for native (JOGL) charts will be discussed here https://github.com/jzy3d/jzy3d-api/issues/136
