### ISSUE TITLE
i cann't find "org.jzy3d.plot3d.builder.concrete.WaterfallTessellator"

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#103]
i'm trying to use 
import org.jzy3d.plot3d.builder.concrete.WaterfallTessellator;
but NetBeans says cann\t find symbol WaterfallTessellator
can anyone help please ?
thank you very much

**Comment by HosamMukhairez** [comment]
![image](https://user-images.githubusercontent.com/15899559/69064810-27c6ae80-0a38-11ea-80d9-e4f20988dd44.png)

**Comment by jzy3d** [comment]
Are you using the latest version of the library? 1.0.2-SNAPSHOT

**Comment by HosamMukhairez** [comment]
No I'm using 1.0.0 ,,,, because that what i found in the website .. please if there is a link to 1.0.2 please provide me with... thank you very much for your exciting and powerful tool

**Comment by jzy3d** [comment]
You should use Maven to configure your project (see info [here](http://www.jzy3d.org/download-0.9.1.php)) and configure for version 1.0.2
