### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#104]
// Create a drawable scatter with a colormap
        ScatterMultiColor scatter = new ScatterMultiColor(points, new ColorMapper(new ColorMapRainbow(), -0.5f, 0.5f));

// Create a chart and add scatter
        Chart chart = new Chart(Quality.Advanced);
        **chart.getAxeLayout().setMainColor(Color.WHITE);**
        chart.getView().setBackgroundColor(Color.BLACK);
        chart.getScene().add(scatter);
        ChartLauncher.openChart(chart);//*/

the error is "Exception in thread "main" java.lang.NullPointerException" in  chart.getAxeLayout().setMainColor(Color.WHITE);

**Comment by jzy3d** [comment]
Most probably solved by following 

https://github.com/jzy3d/jzy3d-api/issues/105
