### ISSUE TITLE
ERROR org.jzy3d.chart.factories.ChartComponentFactory  - No default frame could be found 

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#105]
when i run the following code it throughs the following error:
0 [main] ERROR org.jzy3d.chart.factories.ChartComponentFactory  - No default frame could be found for the given Chart canvas: class org.jzy3d.plot3d.rendering.canvas.VoidCanvas

the code :

Mapper mapper = new Mapper() {
            public double f(double x, double y) {
                return 10 * Math.sin(x / 10) * Math.cos(y / 20) * x;
            }
        };

// Define range and precision for the function to plot
        Range range = new Range(-150, 150);
        int steps = 50;

// Create a surface drawing that function
        Shape surface = Builder.buildOrthonormal(new OrthonormalGrid(range, steps, range, steps), mapper);
        surface.setColorMapper(new ColorMapper(new ColorMapRainbow(), surface.getBounds().getZmin(), surface.getBounds().getZmax(), new Color(1, 1, 1, .5f)));
        surface.setFaceDisplayed(true);
        surface.setWireframeDisplayed(false);
        surface.setWireframeColor(Color.BLACK);

// Create a chart and add the surface
        Chart chart = new Chart(Quality.Advanced);
        chart.getScene().getGraph().add(surface);
        ChartLauncher.openChart(chart);

**Comment by jzy3d** [comment]
Yes, this is because you are not initializing the chart properly.

Look at this [surface demo](https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-tutorials/src/main/java/org/jzy3d/demos/surface/SurfaceDemo.java).

You have to initialize the chart that way as follow

`Chart chart = AWTChartComponentFactory.chart(Quality.Advanced, "newt");`
