### ISSUE TITLE
java.lang.ClassCastException: class org.jzy3d.plot3d.rendering.canvas.VoidCanvas cannot be cast to class javax.swing.JPanel

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#106]
when i run the following code it throughts the following error
java.lang.ClassCastException: class org.jzy3d.plot3d.rendering.canvas.VoidCanvas cannot be cast to class javax.swing.JPanel (org.jzy3d.plot3d.rendering.canvas.VoidCanvas is in unnamed module of loader 'app'; javax.swing.JPanel is in module java.desktop of loader 'bootstrap')

the code:
String canvasType = "swing";
            // Create a test chart.
            int size = 100000;
            Coord3d[] points = new Coord3d[size];
            for (int i = 0; i < size; i++) {
                points[i] = new Coord3d(
                        (float) Math.random() - 0.5f,
                        (float) Math.random() - 0.5f,
                        (float) Math.random() - 0.5f);
            }
            Scatter scatter = new Scatter(points);
            scatter.setColor(Color.BLUE);

            Chart chart = (canvasType != null ? new Chart(canvasType) : new Chart());
            //chart.getAxeLayout().setMainColor(Color.WHITE);
            chart.getView().setBackgroundColor(Color.BLACK);
            chart.getScene().add(scatter);
            //chart.addController(new CameraMouseController());

            // Embed into Swing.
            JFrame frame = new JFrame();

            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().setLayout(new BorderLayout());
            JPanel panel = new JPanel();
            panel.setLayout(new BorderLayout());
            panel.setOpaque(false);
            panel.setPreferredSize(new Dimension(300, 300));
            panel.setBorder(new MatteBorder(5, 5, 5, 5, java.awt.Color.BLACK));
            if (chart.getCanvas() instanceof Canvas) {
                System.out.println("Canvas " + chart.getCanvas());
                panel.add((Canvas) chart.getCanvas());
            } else if (chart.getCanvas() instanceof Panel) {
                System.out.println("Panel " + chart.getCanvas());
                panel.add((Panel) chart.getCanvas());
            } else {
                System.err.println("Other " + chart.getCanvas());
                panel.add((JPanel) chart.getCanvas());
            }
            frame.getContentPane().add(panel, BorderLayout.CENTER);
            frame.pack();
            frame.setTitle(canvasType);
            frame.setVisible(true);

**Comment by jzy3d** [comment]
Solved by following advice given in

https://github.com/jzy3d/jzy3d-api/issues/105
