### ISSUE TITLE
how to customize Mapper

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#108]
in jzy3d mapper functions works as follow for example
Mapper mapper = new Mapper() {
            @Override
            public double f(double x, double y) {
                System.out.println("x:" + x + " y:" + y + " z:" + (x * Math.sin(x * y)));
                return x * Math.sin(x * y);
            }
        };
then its passed to 
final Shape surface = Builder.buildOrthonormal(new OrthonormalGrid(range, steps, range, steps), mapper);

how can i customize mapper so they can map x,y,z values read from external file 
this is very important issue for me ...

thank you all for improving this tools with your explanations

best regards

**Comment by jzy3d** [comment]
Please use the forum or stackoverflow to ask questions. The issue manager is for declaring bugs.

Concerning your question : the best is to load coordinates from the file and then use the delaunay tesselation to build the surface. Delaunay tesselation is described in the developer guide : http://jzy3d.org/guide.php
