### ISSUE TITLE
Calling Scatter through exception

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#110]
when i use the following declaration
Scatter scatter = new Scatter(points, colors, size);

it throughts the following exception 
java.lang.NullPointerException

every thing was going and working fine since one month ago and all input parameter is fulled and checked successfully , but suddenly this exception always appears and i can't continue my work using jzy3d

anyone has an idea what is the problem

**Comment by jzy3d** [comment]
You should indicate the entire stack trace to help understanding your problem.
