### ISSUE TITLE
Code-style and formatting rules for jzy3d

### ISSUE THREAD

**Issue by HannesWell** [jzy3d/jzy3d-api#112]
Hello,

I used jzy3d in a project and I like it. Great work.
Nevertheless I had to workaround/fix some bugs and also made improvements that I want to commit to this project.

Therefore I want to ask for code-style and formatting rules for this project.
I noticed already that you use four spaces instead of one tab and define the fields of a class at the bottom. Do you also have any line-length limitations for code or comments?
As far as I can tell apart from that the applied formats looks like the (Eclipse) defaults?
But especially the SWT-project is not formatted consistently (I could fix that with my commits).

I want to use Eclipse. So in case you have an Eclipse Formatter already I would be happy if you could provide me with that formatter.

**Comment by jzy3d** [comment]
Hi, 

Thanks for asking. I indeed rely on the default Eclipse formatter with few edits
- I make line be as long as 360 characters to ensure line are not splitted (I dislike splitted lines, especially on wide screens!). 
- I use four spaces instead of tabs.

I am not answering with my usual dev computer so I can't provide you that formatter right now unfortunately.

**Comment by HannesWell** [comment]
Allright, thanks for that information. This helps already so I can start.
If you can provide me the formatter later I can apply it afterwards. The changes shouldn't be too big then.

**Comment by jzy3d** [comment]
Hello,

Thanks for your suggestion of adding formatter file to the project. I like the google formatters so I saved the Eclipse and Intellij formatters in doc/style/ of this repository at this commit https://github.com/jzy3d/jzy3d-api/commit/2bc67d0f803d8bf11b1e93a72a34653aa0766bad

**Comment by HannesWell** [comment]
Have you also considered to use the Eclipse clean-up respectively Eclipse safe-actions?
They offer many possibilities to clean up the code, which I personally really like. You can see them in the Preferences under Java -> Editor -> SaveActions.
You can either run the clean up as dedicated task using a clean-up profile (like in Java -> Code Style -> Clean Up) or as Save Actions. Unfortunately you cannot run the clean-up as SaveAction but when you use an Eclipse-Oomph Setup this can be automatically set up to be equivalent.
