### ISSUE TITLE
Problem in Mapper class

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#113]
when I prepare the mapper function 
I first prepare the min x , max x , step x , step y as follow
            // Define range and precision for the function to plot            
            rangeX = new Range((float) 0, (float) 5);
            stepsX = Double.valueOf((5- 0) / (0.8)).intValue() + 1;
            rangeY = new Range((float) 0, (float) 5);
            stepsY = Double.valueOf((5- 0) / (0.8)).intValue() + 1;

the original point as follow
x ; y ; z
0 ; 0 ;-120.00
1 ; 0 ;1472.00
2 ; 0 ;1056.00
3 ; 0 ;7720.00
4 ; 0 ;-2808.00
5 ; 0 ;-6160.00

by using the step factor = 0.8
the new x points must be like this :  
0.8
1.6
2.4
and so on

but what appears is like this : 
0.83
1.66
2.49

there is difference = 0.03 
why this problem happens?

**Comment by jzy3d** [comment]
Can you provide a program that generate the unexpected grid values ?

**Comment by HosamMukhairez** [comment]
it's hard to submit all code here because I'm using more than one class to prepare points in Coord3d[] and I'm using hash map "hashMapDeepness" which is filled from outside class inside the Mapper class as follow
Mapper mapper1 = new Mapper() {
            @Override
            public double f(double x, double y) {
                return ((Double.valueOf(hashMapDeepness.get(x +":"+ y) + "")));
            }
        };

actually before 3 days everything was normal .... suddenly the differences appeared... I'm using maven java project with repository 
<repositories>
        <repository>
            <id>jzy3d-snapshots</id>
            <name>Jzy3d Snapshots</name>
            <url>http://maven.jzy3d.org/snapshots</url>
        </repository>
        <repository>
            <id>jzy3d-releases</id>
            <name>Jzy3d Snapshots</name>
            <url>http://maven.jzy3d.org/releases</url>
        </repository>                                      
    </repositories>

and dependencies
<dependency>
            <groupId>org.jzy3d</groupId>
            <artifactId>jzy3d-api</artifactId>
            <version>1.0.3-SNAPSHOT</version>            
            <type>jar</type>
</dependency>

**Comment by HosamMukhairez** [comment]
excuse me ... but i need my problem to be solved ... i didn't buy the tools before 10 days to stuck is such trivial problem ...

I can't go forward in my project

please any suggestions ??

best regards

________________________________

**Comment by jzy3d** [comment]
The API code has not changed for weeks, so if it is not working since 3 days, it is most probably due to your own code.

You do not provide anything sufficient to understand the problem so I can't help you.

Maybe you can avoid this problem by writing your own implementation of OrthonormalGrid. You could provide the stepLength parameter you wish to define, instead of passing a number of steps that is then used to define the stepLength.

Last, if I wanted to understand the problem deeply I would simply add breakpoints in OrthonormalGrid to check how stepLength is computed w.r.t to your input parameters.

**Comment by HosamMukhairez** [comment]
I'll try support the needed code to run the project to recognize the problem
========================
here is init() function 
@Override
    public void init() {
        // Define a function to plot
        Mapper mapper = new Mapper() {
            @Override
            public double f(double x, double y) {                
                return ((Double.valueOf(hashMapDeepness.get(x +":"+ y) + "")));
            }
        };

            Range rangeX = new Range((float) 0, (float) 5);
            int stepsX = Double.valueOf((5- 0) / (0.8)).intValue() + 1;
            Range rangeY = new Range((float) 0, (float) 4);
            int stepsY = Double.valueOf((4- 0) / (0.8)).intValue() + 1;//*/

        // Create the object to represent the function over the given range.
        Shape surface = Builder.buildOrthonormal(new OrthonormalGrid(rangeX, stepsX, rangeY, stepsY), prepareCoordinateMapper());
        surface.setColorMapper(new ColorMapper(new ColorMapRainbow(), surface.getBounds().getZmin(), surface.getBounds().getZmax()));
        surface.setFaceDisplayed(true);
        surface.setWireframeDisplayed(true);
        surface.setWireframeColor(Color.BLACK);

        // Create a chart and add surface
        chart = initializeChart(Quality.Advanced);
        chart.getScene().getGraph().add(surface);

        // Setup a colorbar
        AWTColorbarLegend cbar = new AWTColorbarLegend(surface, chart.getView().getAxe().getLayout());
        cbar.setMinimumSize(new Dimension(100, 600));
        surface.setLegend(cbar);
    }//*/



the hashMapDeepness object in Mapper is filled as follow
{0.0:0.0=-3.85, 
4.8:0.0=-0.08, 
0.0:3.2=-0.03, 
0.0:4.0=-0.07, 
4.8:3.2=-0.3, 
4.8:4.0=-7.66, 
3.2:4.0=-0.31, 
3.2:3.2=-0.24, 
3.2:2.4=-0.34, 
4.8:0.8=-0.39, 
3.2:1.6=-0.47, 
4.8:1.6=-0.5, 
3.2:0.8=-0.24, 
4.8:2.4=-0.28, 
1.6:4.0=-0.11, 
1.6:3.2=-0.02, 
1.6:2.4=-0.02, 
1.6:0.0=-0.65, 
2.4:0.8=-0.13, 
3.2:0.0=-0.15, 
0.0:1.6=-0.06, 
2.4:2.4=-0.09, 
0.0:2.4=-0.04, 
2.4:1.6=-0.12, 
2.4:4.0=-0.18, 
0.0:0.8=-0.83, 
2.4:3.2=-0.09, 
1.6:1.6=-0.05, 
1.6:0.8=-0.16, 
2.4:0.0=-0.51, 
0.8:0.8=-0.16, 
0.8:2.4=-0.02, 
0.8:1.6=-0.04, 
0.8:0.0=-1.15, 
0.8:4.0=-0.09, 
4.0:0.0=-0.2, 
0.8:3.2=-0.02, 
4.0:4.0=-0.56, 
4.0:3.2=-0.87, 
4.0:0.8=-1.22, 
4.0:2.4=-0.71, 
4.0:1.6=-0.92}

**Comment by HosamMukhairez** [comment]
any idea about the problem ???

**Comment by HosamMukhairez** [comment]
even when i use the same code above but instead of 0.8 i used 0.7
the output displays like this
x:0.0 y:1.7142857142857144

but the correct output must be like this 
x:0.0 y:1.7

where is the problem ?
