### ISSUE TITLE
Error in using IncrementalDelaunayDemo

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#114]
I bought jzy3d... and when i use the example code of class IncrementalDelaunayDemo from "run" method 
everything is fine ...

but when i replace the lines  inside "run"
                    ```

> // Adding random points
>                     double a = rng.nextDouble() * 2 * Math.PI;
>                     double r = Math.sqrt(rng.nextDouble()) * 8; // sqrt for uniform distribution
>                     double x = Math.cos(a) * r;
>                     double y = Math.sin(a) * r;
>                     double r0 = Math.sqrt(Math.pow(x, 2) + Math.pow(y, 2));
>                     double r1 = Math.sqrt(Math.pow(x - 2, 2) + Math.pow(y + 2, 2));
>                     double r2 = Math.sqrt(Math.pow(x - 4, 2) + Math.pow(y - 5, 2));
>                     double r3 = Math.sqrt(Math.pow(x + 4, 2) + Math.pow(y + 2, 2));
>                     double u = Math.sin(Math.atan2(x, y) + r0);
>                     double z
>                             = 6 / (1 + Math.abs(u)) // double spiral
>                             - 2 / (1 + Math.abs(r0)) // hole
>                             - 10 / (1 + Math.abs(r1))
>                             + 10 / (1 + Math.abs(r2)) // peak
>                             + 8 / (1 + Math.abs(r3))
>                             + .5 * (Math.cos(x) + Math.sin(y)) // waves
>                             ;

```

by my own values for x,y,z ...... it through exception
i read the values for x,y,z from file inside the "run" method
x,y,z
0,0,123
0,1,201
0,2,95
1,0,88
1,1,103
1,2,140

the exception "java.lang.NullPointerException" at line 
List<Polygon> polygons = new ArrayList<Polygon>(triangulation.trianglesSize());

despite of i created 
triangulation.insertPoint(new il.ac.idc.jdt.Point(x, y, z));
before the exception line

anyone can explain the problem ? and solve it please?

**Comment by jzy3d** [comment]
You probably forgot to initialize the "triangulation" instance or forgot to feed it with points.

**Comment by HosamMukhairez** [comment]
Actually I initialized "triangulation" ,, but how i solved the problem .. I added initial values to "triangulation" as shown below
triangulation.insertPoint(new il.ac.idc.jdt.Point(0, 0, 0));

I don't know why ,, but at least that worked with me.

**Comment by HosamMukhairez** [comment]
I found one article in internet solved this problem
instead of using "triangulation" it's better to use the following code
List<Polygon> polygons = new ArrayList<>();
                        for (int i = 0; i < distDataProp.length - 1; i++) {
                            for (int j = 0; j < distDataProp[i].length - 1; j++) {                                
                                Polygon polygon = new Polygon();
                                polygon.add(new Coord3d(i, j, distDataProp[i][j]));
                                polygon.add(new Coord3d(i, j + 1, distDataProp[i][j + 1]));
                                polygon.add(new Coord3d(i + 1, j + 1, distDataProp[i + 1][j + 1]));
                                polygon.add(new Coord3d(i + 1, j, distDataProp[i + 1][j]));
                                polygons.add(polygon);                                
                            }
                        }

which works more effectively than "triangulation" as I seen.

By using this code you can add polygons more easily and more stable

NOTE: distDataProp is "double[][] distDataProp = new double[15][15];"
you have to fill it by using another loop according to your project logic

I hope it helps all of us
