### ISSUE TITLE
deleting points from "triangulation"

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#115]
When I use 
 triangulation.insertPoint(new il.ac.idc.jdt.Point(x, y, z));

it works fine 

but when i use 
triangulation.deletePoint(p);
where "p" is already insreted point in "triangulation" object

the code through the following exception 
"Error: can't delete a point on the perimeter"

When this problem appears ? is there any suggested solution ?

**Comment by HosamMukhairez** [comment]
Instead of using "triangulation" I used the following code 
List<Polygon> polygons = new ArrayList<>();
                        for (int i = 0; i < distDataProp.length - 1; i++) {
                            for (int j = 0; j < distDataProp[i].length - 1; j++) {
                                Polygon polygon = new Polygon();
                                polygon.add(new Coord3d(i, j, distDataProp[i][j]));
                                polygon.add(new Coord3d(i, j + 1, distDataProp[i][j + 1]));
                                polygon.add(new Coord3d(i + 1, j + 1, distDataProp[i + 1][j + 1]));
                                polygon.add(new Coord3d(i + 1, j, distDataProp[i + 1][j]));
                                polygons.add(polygon);                                
                            }
                        }

NOTE : distDataProp  is double[][] distDataProp = new double[15][15];
In my project logic I read points from serial port (real time stream) and after 15 times read I don't need to delete points from array I just shift the points one step to the right and fill the 16 time point to index 15 of the array

I hope this helps every body

**Comment by jzy3d** [comment]
Yes, this is covered in section "Surface defined by polygons" in the user guide.

Triangulation is for applying the Delaunay tesselation algorithm when you don't know how to build the mesh out of your input points. If you know your x/y grid, it is easier to use Polygons (and also to reuse them when you only change Z values).
