### ISSUE TITLE
updating z axis scale automatically

### ISSUE THREAD

**Issue by HosamMukhairez** [jzy3d/jzy3d-api#116]
I read data from serial port ,, I prepare these data and pass it to surface as follows 
```
double z = 0;
                        minimumZ = 0;
                        maximumZ = 0;
                        // Build a polygon list                                                
                        List<Polygon> polygons = new ArrayList<>();
                        for (int i = 0; i < distDataProp.length - 1; i++) {
                            for (int j = 0; j < distDataProp[i].length - 1; j++) {
                                z = distDataProp[i][j];
                                Polygon polygon = new Polygon();
                                polygon.add(new Coord3d(i, j, distDataProp[i][j]));
                                polygon.add(new Coord3d(i, j + 1, distDataProp[i][j + 1]));
                                polygon.add(new Coord3d(i + 1, j + 1, distDataProp[i + 1][j + 1]));
                                polygon.add(new Coord3d(i + 1, j, distDataProp[i + 1][j]));
                                polygon.updateBounds();
                                polygons.add(polygon);
                                if (z <= minimumZ) {
                                    minimumZ = z;
                                } else if (z >= maximumZ) {
                                    maximumZ = z;
                                }
                            }
                        }
```

and every time I calculate the minimum and maximum z values
I want the chart to automatically update it's z axis scale according the incoming values of  z
I tried the following solutions (but none of them worked at all)
1. surface.getBounds().setZmax((float) maximumZ);
                        surface.getBounds().setZmin((float) minimumZ);

2. chart.getView().setBoundManual(new BoundingBox3d(0, 8, 0, backIndex, (float) minimumZ, (float) maximumZ));
                        chart.getView().shoot();

what I need is to update the z axis as if I do it by mouse scroll.

Best regards

**Comment by jzy3d** [comment]
`chart.getView().updateBounds()` will update the view bounds based on the scene graph bounds (hence, it will consider your object changes that happened while calling `polygon.updateBounds()` before).

Concerning your code example, I advice you to reuse the same polygons instead of building new polygons each time you receive data on your serial port.

One way to do it is to use a function like below for each existing polygon

```
public void remapPolygon(Polygon p, float zValue) {
	for(int i=0; i<p.size(); i++){
		Point pt = p.get(i);
		Coord3d c = pt.xyz;
		c.z = zValue;
	}
}
```

You might see examples of animating surfaces in the guide demo `AnimatedSurfaceDemo`

**Comment by jzy3d** [comment]
Please use the forum for questions. The issue tracker is rather for bugs.
