### ISSUE TITLE
One of LineStripInterpolated constructor miss to call the default constructor (hence no line at all is built)

### ISSUE THREAD

**Issue by maf123sp** [jzy3d/jzy3d-api#121]
The constructor LineStripInterpolated::LineStripInterpolated(IInterpolator interpolator, List<Coord3d> controlPoints, int resolution); has a wrong implementation.

Currently, there is no functionality assigned. Instead it should contain a forward to

LineStripInterpolated(IInterpolator interpolator, List<Coord3d> controlPoints, int resolution) {
this(interpolator, controlPoints, resolution,false);
}

This solves all issues with the Interpolation demo.

**Comment by jzy3d** [comment]
Will be available in Jzy3d 2.0.0
