### ISSUE TITLE
[EmulGL] Improve rendering quality on HiDPI Windows10

### ISSUE THREAD

**Issue by jzy3d** [jzy3d/jzy3d-api#140]
Below chart shows an aliasing improvement required on a chart rendered in Windows10 with HiDPI configuration.

![image](https://user-images.githubusercontent.com/2334960/106669735-6187c480-65ac-11eb-8a9f-5cb345a7bcb4.png)

Using CPU based rendering with this aliasing glitch remains a good workaround for the badly scaled native charts with GPU based rendering (which issue can be found here https://github.com/jzy3d/jzy3d-api/issues/101)

To reproduce thi aliasing problem
- Run SurfaceDemoEmulGL or ScatterDemoEmulGL from tutorials
- Use Windows10 with HiDPI configuration

**Comment by jzy3d** [comment]
Interesting comparison of [offscreen painting vs onscreen painting quality](https://stackoverflow.com/questions/45176241/miserable-text-when-drawing-offscreen-images-in-java)

**Comment by vsonnier** [comment]
Maybe it is related with this JFreeChart issue : https://github.com/jfree/jfreechart/issues/170 and a possible fix ?

**Comment by jzy3d** [comment]
Applying the trick suggested by @vsonnier allows improving the pixel ratio (everything looks thiner), however, it does not deal with the aliasing effect. See work in progress in "hipdpi" branch.

<img width="361" alt="Capture d’écran 2021-02-02 223605" src="https://user-images.githubusercontent.com/2334960/106665981-45cdef80-65a7-11eb-9193-445d198ab545.png">

**Comment by jzy3d** [comment]
Disabling @vsonnier suggestions, then applying [the idea of reseting the internal JVM Graphics2D scaling to 1](https://stackoverflow.com/questions/43057457/jdk-9-high-dpi-disable-for-specific-panel) lead to a too small image but with no aliasing issue.

![image](https://user-images.githubusercontent.com/2334960/106668073-1bc9fc80-65aa-11eb-920b-218d464d9ef3.png)

**Comment by jzy3d** [comment]
Replacing 
```
Image i = glImage.getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);
g.drawImage(i, StartX, StartY, o);

```
by
```
Image i = glImage;
g.drawImage(glImage, StartX, StartY, desiredWidth, desiredHeight, o);

```
provides the expected result.

![image](https://user-images.githubusercontent.com/2334960/106669592-33a28000-65ac-11eb-8dac-29630f91b98e.png)

**Comment by jzy3d** [comment]
Works on MacOS as well, but noticed a rendering performance slightly larger (pixel ratio is 2x on MacOs with Retina, 1.5x on my windows running on Apple hardware with Bootcamp).

**Comment by jzy3d** [comment]
Can be edited with chart's Quality setting.
