### ISSUE TITLE
Improve structure and clean-up pom.xml 

### ISSUE THREAD

**Issue by HannesWell** [jzy3d/jzy3d-api#153]
While going through the code I noticed that the pom.xml could be improved in the following ways:
- for some plugins executed during build the version element is missing, this is bad because it makes builds environment depended (e.g. from Maven version used).
- some dependencies of child-modules are specified including their version in multiple child poms (for example the dependency to `org.jogamp.gluegen` in `jzy3d-native-jogl-core` and `jzy3d-native-jogl-awt`). I suggest to create a `dependencyManagement`-element in the root pom.xml where each dependency of all modules are listed with only their `groupId`, `artifactId`, `version`. This allows to manage the versions of all dependencies of the library from the root pom without the danger of having dependencies to different versions in different jzy3d modules.
- add a pluginManagement element in the root pom.xml to manage the versions of all plugins executed during build of the library. This has the same intention like the previous point and avoids the need for a property for each plugin.
- upgrade from hamcrest-core:1.3.0 and hamcrest-library:1.3.0 to hamcrest-2.2.0 (hamcrest-core and hamcrest-library were merged) and make it available for the entire library (so specify it as test-dependency in the root pom).
- update to mockito 3.8.0 and make it available in the entire library
- enable/disable integration tests via a profile or property to avoid commenting them in and out.
- remove empty elements

If you want the suggested improvements I can offer to implement them.

**Comment by jzy3d** [comment]
Hi Hannes, I agree to most of your suggestions.

Note that
- JOGL should not be known by all JARS : as shown in the below diagram, the core is generic, Emulgl do not know JOGL and only jGL, and Native implementation must know JOGL. The good fix would be to keep jogl in jzy3d-native-jogl-core and remove JOGL from jzy3d-native-jogl-awt as this later module has a dependency on the former. I started doing this clean but encountered a weird dependency issue that lead [to unavailable SWT dependency](https://github.com/jzy3d/jzy3d-api/actions/runs/714202678).
- I would LOVE some help on disabling/enabling the integration test more smartly. I also thought about profiles and found that FailSafe Maven plugin is intended to deal with integration tests. It has nice -skipITTest flag that make things clear when trying to build - but using profiles is a good solution as well. As mentioned [here](https://github.com/jzy3d/jzy3d-api/#how-to-build) I tried using FailSafe to register and execute ITTest* but this failed on my Mac. I tried to [explain my difficulties in the master pom](https://github.com/jzy3d/jzy3d-api/blob/master/pom.xml#L160) where test name patterns are defined for both surfire and failsafe. 

Beside that I agree with all your suggestion and would like to thank you a lot for your contributions!

![image](https://user-images.githubusercontent.com/2334960/113478483-51477500-9489-11eb-92e5-489399c049b5.png)

**Comment by HannesWell** [comment]
Ok, great. So I will to work on it and consider your points.

Regarding a `dependencyManagement`-element in the root pom: Such element only `configures` the contained dependency but does not specifies them as a dependency. If a child module then actually specifies a dependency in a dependencies-element it inherits the configuration from the parent pom. With that the versions of all possible dependencies can be specified in the root pom (at one location). If a child module then really has a dependency it only specifies it with its `groupId` and `artifactId` (without a version). On this way it is guaranteed that the same version is used in the whole library and when updating dependencies only one string needs to be changed.
See
https://stackoverflow.com/questions/2619598/differences-between-dependencymanagement-and-dependencies-in-maven

**Comment by HannesWell** [comment]
Is there an inevitable reason why the `jzy3d-tutorials` module does not inherit its configuration from the root jzy3d-all module?
I haven't look into to great details but from a quick comparison it looks like there are many duplication's (that seem to be gone out of sync?).
If there is no such reason I would try to let `jzy3d-tutorials` inherit from `jzy3d-all` save the text for the common elements and overwrite what's different.

Another thing for testing: Which _use cases_ of the build have to work?
- mvn clean verify
- to run the integration tests I have to un-comment `<include>**/ITTest*.java</include>` in the surefire-plugin configuration but you stated that they are likely to fail.

Are there more use-cases? If spotted a `disable-java8-doclint` profile but is this used anyhow?

**Comment by jzy3d** [comment]
Yes there is a reason for this : the tutorial is intended to be reusable as is with the correct maven settings to hit the good repo and the good dependencies. Repeating all info available in jzy3d-all is made on purpose for the demo. Anybody can copy the subproject and start in a few second.  

I kept the tutorial in the API folder to avoid having one more external repo with the same lifecycle but involving a separate git management (in other word, I want to minimize the number of git commit/pull). 

For the build use case

- compile locally 
- deploy to maven repo via ftp
- build source, doc and test jars to publish them in maven repo
- generate html javadoc folders (hence the doclint config for mvn javadoc:javadoc)
- added cobertura to get a coverage score - but I am having difficulties to run it properly with java 11+ on my mac.

**Comment by jzy3d** [comment]
Hi, if you read this section about [HiDPI with EmulGL](https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-emul-gl/README.md#hidpi), you may think that other use case for the build could be
* have profiles for executing tests with a particular JVM
* have profiles for executing tests that have been made on a specific computer

This is not a requirement at all, this is just an idea to share. The difficulty of testing HiDPI is not only due to the build tool limitation but first by the fact that offscreen chart do not make use of HiDPI seamingly, and I would need to tackle this.

**Comment by HannesWell** [comment]
Yes I have no doubt HiDPI testing is not easy.
And yes I think it is feasible to create different profiles for different scenarios. As you probably already notices profiles can be activated for a particular JVM (like you already used for doclint) but the can also be activated by a property or a combination of both. But the property must be known before the poms are parsed so it must either be specified as CLI argument (using `-DpropertyName=value`) or in the `.mvn/maven.config` file. Or you simple activate the profile explicitly (using -PprofileName).

The profile would then have a surefire- or failsafe-plugin (probably the first one) that includes the corresponding HiDPI tests. The key point is that those HiDPI tests are not executed by the default surefire run.
This can be achieved by either using a filename that does not match the [default includes pattern of surefire](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#includes) or must be explicitly [excluded](https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#excludes). So if you use a naming pattern like `HiDIPTest*.java` this would work. If you want to run different tests for different machines then the name has to reflect this too. For example by using `HiDIPTestLinux*.java`, `HiDIPTestMac*.java`, `HiDIPTestWindows*.java` for different platforms.
This is basically the same like for unit and integration tests.

So bottom-line is: from build-perspetive this can be done quite easily.

**Comment by HannesWell** [comment]
Furthermore while going to all of the POMs/projects I noticed the following points:

- The module `jzy3d-core-swt` is effectively empty.
- There are two AWT modules: `jzy3d-native-jogl-awt` and `jzy3d-core-awt`
- The following modules seem to be provisional on the first sight:
  - `jzy3d-io-reports` (furthermore using the default package is discouraged)
  - `jzy3d-io-xls`
I don't know your plans until the 2.0 release and just wanted to tell that is not forgotten.

Furthermore an overview outlining the inter-dependencies and intentions of all modules would be a nice addition to the charts that show the dependencies of the different interfaces/classes.

**Comment by HannesWell** [comment]
Another think I just noticed:
Is the deployment of the test plug-ins intentionally? Since they are usually not of interests for consumers of the library I suggest to exclude them from deployment into the maven repo. The quick way to achieve this would be to set the property `maven.deploy.skip` `true` in the pom.xml of the corresponding module.

**Comment by HannesWell** [comment]
Closing this, since all tasks of this issue are completed.

Do you have any comments on my previous two remarks? If they are relevant I can other issues for them.
