### ISSUE TITLE
OBJFile throws an exception while loading on Java 8

### ISSUE THREAD

**Issue by jzy3d** [jzy3d/jzy3d-api#177]
**Describe the bug**
Loading a VBO on Java8 lead to an exception. Running with Java9 does not yield to this exception.

```
java.lang.NoSuchMethodError: java.nio.FloatBuffer.rewind()Ljava/nio/FloatBuffer;
	at org.jzy3d.io.obj.OBJFile.compileModel(OBJFile.java:385)
	at org.jzy3d.io.obj.OBJFileLoader.load(OBJFileLoader.java:31)
	at org.jzy3d.io.obj.OBJFileLoader.load(OBJFileLoader.java:13)
```

**Expected**
![image](https://user-images.githubusercontent.com/2334960/119052728-5161ec80-b9c5-11eb-97d6-d0b2b7e2049d.png)

**Reproducibility**
`ObjFileVBODemo` in the developer guide guide.

**Versions (please complete the following information):**
 - Jzy3D : 2.0
 - JVM / JDK: 8

**Comment by Bibi56** [comment]
This must be with a specific java8 version, following works on Windows 10.

> openjdk version "1.8.0_282"
> OpenJDK Runtime Environment (build 1.8.0_282-b08)
> Eclipse OpenJ9 VM (build openj9-0.24.0, JRE 1.8.0 Windows 8.1 amd64-64-Bit 20210120_560 (JIT enabled, AOT enabled)
> OpenJ9   - 345e1b09e
> OMR      - 741e94ea8
> JCL      - ab07c6a8fd based on jdk8u282-b08)

Anyway it's worth checking if DirectBuffers are better than HeapBuffers (IHMO, they are):
```
        static boolean ON_HEAP = false;
        int sizeInCoordinates = pointsToRead * 3; // x, y, z
        vertices_ = ON_HEAP?FloatBuffer.allocate(sizeInCoordinates):
            Buffers.newDirectFloatBuffer(sizeInCoordinates);
        int sizeInIndexes = trianglesToRead * 3; // a triangle has 3 vertex
        this.indices_ = ON_HEAP?IntBuffer.allocate(sizeInIndexes):
            Buffers.newDirectIntBuffer(sizeInIndexes);
```
You can check if you have the issue on your java VM with DirectBuffers.

**Comment by Bibi56** [comment]
By the way, using heap buffers makes debug easier as you can see the values as array, so HeapBuffers are better while debugging.

**Comment by jzy3d** [comment]
Used the BufferUtil class to be address the `NoSuchMethodError` of JVM of various versions.
