### ISSUE TITLE
'AxisLabel' is trying to use Unicode.

### ISSUE THREAD

**Issue by kanjang** [jzy3d/jzy3d-api#188]
Unicode is not available for AXisLabel.

The code contents are as follows:

```
String xLabel = "ωₓ";
chart.getAxisLayout().setXAxisLabel(xLabel);
chart.getAxisLayout().setYAxisLabel("ωᵧ (rad/s)");
chart.getAxisLayout().setZAxisLabel("S(ωₓ,ωᵧ)");
```

It appears as follows:
![image](https://user-images.githubusercontent.com/694663/122898898-3dbff200-d386-11eb-9a4a-e972950468d7.png)

**Comment by jzy3d** [comment]
Sorry I missed this. EmulGL is more powerful than native chart for text management because it uses AWT. Did you try it ?

**Comment by jzy3d** [comment]
Also : I added a more powerful text renderer some time ago , to my memory it is named JOGLTextRenderer2d and can replace the default TextBitmapRenderer of the AxisBox by overriding the factory. This appears in the developer guide.

**Comment by jzy3d** [comment]
This is now supported both for EmulGL charts (as of Jzy3D 2.0.0) and Native charts (as of Jzy3D 2.0.1).

![image](https://user-images.githubusercontent.com/2334960/153853054-c9d1e92a-2ea0-4a32-a831-bcabcf7a39fe.png)

See native chart implementation review [here](https://github.com/jzy3d/jzy3d-api/pull/233).

**Comment by kanjang** [comment]
Wow.
I couldn't use the Unicode, so I made a layer and used the code on it.
I'm glad I can use Unicode.
Thank you.
