### ISSUE TITLE
Access to GLAnimatorControl?

### ISSUE THREAD

**Issue by tferr** [jzy3d/jzy3d-api#213]
With 1.0.3, one could use
```java
GLAnimatorControl control = ((IScreenCanvas) view.getCanvas()).getAnimator();
control.setUpdateFPSFrames(FPSCounter.DEFAULT_FRAMES_PER_INTERVAL, null);
```
But this does not seem to be valid anymore with 2.0.0., what would be the equivalent now?
Is there a better way to call `setUpdateFPSFrames()`?

**Comment by jzy3d** [comment]
Yes, as of 2.0, I have added EmulGL, a CPU renderer for Jzy3D which is an alternative to JOGL. So it has its own animator, and these two type animator are wrapped in IAnimator interface.

I would however recommend to avoid using animator. If you instanciate your chart is `Quality.setAnimated(false)`, this will never repaint chart, unless you change viewpoint, scale etc. This is however not ideal if you intend to animate drawables.

If you really want to use the animator,  
```
IAnimator animator = chart.getCanvas().getAnimation();
FPSAnimator joglAnimator = (FPSAnimator)animator;
joglAnimator.setFPS(value);
```

**Comment by tferr** [comment]
Thanks! The main interest here was to add a String on the upper corner of the canvas reporting GLAnimatorControl#getLastFPS() values. It gives me the impression that certain animations (rotations!?) occur at slower FPS  than others, and I just wanted to have such a 'debug' label to better understand the chart behavior. Do let me know if there are better options to monitor animations's speed.

On the EmulGL: How do you enable it vs JOGL? Sorry if this has been explained elsewhere. I saw the v2.0.0 announcement, but  only now had the time to look into it.

**Comment by jzy3d** [comment]
You just have to change your factory : 

https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-tutorials/src/main/java/org/jzy3d/demos/surface/SurfaceDemoEmulGL.java#L34

readme of emulgl-awt module explains this well.
