### ISSUE TITLE
Missing package chart2d

### ISSUE THREAD

**Issue by rsand-temple** [jzy3d/jzy3d-api#234]
The package org.jzy3d.chart2d.Chart2d does not seem to exist in the distribution. The 2d tutorial depends on it. Has it been removed? Is it still possible to make 2D charts in 2.0.0?

**Comment by jzy3d** [comment]
Hi Richard, 
The 2D package is still part of the distribution (https://github.com/jzy3d/jzy3d-api/tree/master/jzy3d-native-jogl-awt/src/main/java/org/jzy3d/chart2d).

**Comment by jzy3d** [comment]
Hi @rsand-temple ,

The [tutorials involving 2D charts](https://github.com/jzy3d/jzy3d-api/tree/master/jzy3d-tutorials/src/main/java/org/jzy3d/demos/chart2d) have been improved.

This is on master, deployed as 2.0.1-SNAPSHOT. Will be available in a release version in the coming days.
