### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException'

### ISSUE THREAD

**Issue by rsand-temple** [jzy3d/jzy3d-api#243]
Hi - I am trying to get a simple 2d scatter plot to render. I'm experiencing the below error which crashes the JVM.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/Users/rsand1/.m2/repository/org/jogamp/gluegen/gluegen-rt/2.3.2/gluegen-rt-2.3.2.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-02-23 08:49:23.985 java[1479:1684288] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff81ec28f0b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff81e989b9d objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff81ec518ca -[NSException raise] + 9
	3   AppKit                              0x00007ff821603171 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007ff8215eeee6 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1287
	5   AppKit                              0x00007ff8215ee9d9 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   libnativewindow_macosx.jnilib       0x0000000150c0a3fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	7   ???                                 0x0000000116f1e3f0 0x0 + 4679918576
)
libc++abi: terminating with uncaught exception of type NSException
```
The code I am executing is:

```
	Chart2d chart = new Chart2d();
	chart.add(scatter(points, color).getDrawable());
	chart.open();
...
	private static ScatterSerie2d scatter(double[][] points, Color color) {
		int size = points.length;

		List<Coord2d> coord = new ArrayList<>();

		for (int i = 0; i < size; i++)
			coord.add(new Coord2d(points[i][0], points[i][1]));

		ScatterSerie2d scatter = new ScatterSerie2d("Scatter2D");
		scatter.add(coord);
		scatter.setColor(color);
		scatter.setWidth(3);
		return scatter;
	}

```

Appreciate any advice. Thanks!

**Comment by jzy3d** [comment]
Could you clarify your Jzy3D version and Operating System version?

I am currently working on Jzy3D 2.0.1 branch, which uses JOGL 2.4-rc4, which solves multiple compatibility problems for MacOS. This [ticket](https://github.com/jzy3d/jzy3d-api/issues/128) seams related to your issue.

This 2.0.1 is still a work in progress but I may deploy a snapshot version in the coming days if this solves your issue.

**Comment by rsand-temple** [comment]
Yes it’s 2.0.0 on OSX so likely the exact same issues.

On Feb 24, 2022, at 8:20 AM, jzy3d ***@***.***> wrote:

﻿

Could you clarify your Jzy3D version and Operating System version?

I am currently working on Jzy3D 2.0.1 branch, which uses JOGL 2.4-rc4, which solves multiple compatibility problems for MacOS. This ticket<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjzy3d%2Fjzy3d-api%2Fissues%2F128&data=04%7C01%7Crichard.sand0001%40temple.edu%7C066ba3fc86f64ab61ea508d9f79875ce%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637813056464206045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6rW9YiqDMTNjjwqbAxfMVh2CHiJTUgX4RPsC%2FbkPk20%3D&reserved=0> seams related to your issue.

This 2.0.1 is still a work in progress but I may deploy a snapshot version in the coming days if this solves your issue.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjzy3d%2Fjzy3d-api%2Fissues%2F243%23issuecomment-1049853565&data=04%7C01%7Crichard.sand0001%40temple.edu%7C066ba3fc86f64ab61ea508d9f79875ce%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637813056464206045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pnjR5G%2B4xjmcAetsrULwfCoJFohkULmtO6erpE79g3c%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWTBGSGPWWLMQQEPFNZJJRTU4YWCVANCNFSM5PHKYN7A&data=04%7C01%7Crichard.sand0001%40temple.edu%7C066ba3fc86f64ab61ea508d9f79875ce%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637813056464206045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FNWOmlrXHFzIY8E8%2Fnzrs7bAiWmMNyEIqFJmvxGaYmg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crichard.sand0001%40temple.edu%7C066ba3fc86f64ab61ea508d9f79875ce%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637813056464206045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o9neNBfMEt92OjukYgVR%2B%2Bp1EofXB46nWil2cIm7ZVA%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crichard.sand0001%40temple.edu%7C066ba3fc86f64ab61ea508d9f79875ce%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637813056464206045%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UyDYXMmbMHM0Prt7rwbrH0dLVat867aEVnTjP8wSe7I%3D&reserved=0>.

**Comment by jzy3d** [comment]
The warning about illegal reflective access is not the cause to your problem. 

There is a link to a solution in [this issue](https://github.com/jzy3d/jzy3d-api/issues/142).

**Comment by jzy3d** [comment]
Just changed the title so that it clarify your real issue.

While waiting for the deployement of 2.0.1 snapshot version, you may wish to use `EmulGLChartFactory` instead of `AWTChartFactory`. This performs CPU rendering in full java and prevents from exceptions related to the use of native libraries (using the GPU).

**Comment by jzy3d** [comment]
@rsand-temple , I have deployed 2.0.1-SNAPSHOT, which will use JOGL 2.4-rc4, hence will work on your macOS.

You can use `AWTChartFactory` again.

Using a simple Scatter object made for 3D plot and then invoking chart.view2d() to use a 2D layout works well if you can't have the above code working.

**Comment by jzy3d** [comment]
I close since it duplicates https://github.com/jzy3d/jzy3d-api/issues/128 which will remain open until 2.0.1 is released.
