### ISSUE TITLE
Can't run demos on M1

### ISSUE THREAD

**Issue by Sternbach-Software** [jzy3d/jzy3d-api#296]
**Describe the bug**
I downloaded [this demos archive](http://download.jzy3d.org/api/1.0/jzy3d-guide-1.0-demos-exe.zip) on my Mac M1 Air, extracted the zip, opened the terminal to the folder, ran "java -classpath "lib/*" org.jzy3d.demos.browser.DemoBrowser", and got the exception `java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/cw/fhv2ffj52bn7wtd9_l8m47fc0000gn/T/jogamp_0000/file_cache/jln14372713835448460608/jln10012875064943021176/natives/macosx-universal/libgluegen-rt.jnilib`. Tried importing it into Intellij following [this](https://jogamp.org/wiki/index.php/Setting_up_a_JogAmp_project_in_your_favorite_IDE#Add_a_library_dependency_to_your_project) tutorial from JOGAMP and it didn't work.

**Versions (please complete the following information):**
 - Jzy3D 1.0.0
 - JVM / JDK: Azul 17
 - GPU: M1
 - OS: MacOS Monterey 12.4

**Comment by jzy3d** [comment]
Hi,

M1 is supported as of [2.1.0](http://jzy3d.org/download-2.1.0.php). There is indeed no downloadable demo as you could find for 1.0 - hope I can do something similar soon.

In the meantime you may look at the new guide in progress here that will show lot of the demo you can find in the developer [guide](https://doc.jzy3d.org/guide/docs/getting-started-charts). 

If you have been trying to check if M1 is supported, be confident : the guide picture have been generated with an M1.
