### ISSUE TITLE
Usage of not-allowed java preserved keywords in jar-file-names breaks usage of jzy3d

### ISSUE THREAD

**Issue by orat** [jzy3d/jzy3d-api#314]
**Describe the bug**
jzy3d creates jar-files with "native" in the filename. If these jar-files are included in the classpath exceptions as follow are thrown, e.g. :

java.lang.module.FindException: Unable to derive module descriptor for /home/oliver/JAVA/PROJECTS/DSL4GeometricAlgebra/DSL4GA_Standalone/target/modules/jzy3d-native-jogl-swing.jar
Caused by: java.lang.IllegalArgumentException: jzy3d.native.jogl.swing: Invalid module name: 'native' is not a Java identifier

I assume the that usage of any reserverd keywords, see

https://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.9

produces similar problems.

**Reproducibility**
The principal problem is described also e.g. 

https://github.com/oracle/graal/issues/4620

or 

https://stackoverflow.com/questions/46501388/unable-to-derive-module-descriptor-for-auto-generated-module-names-in-java-9

Steps to reproduce the behavior if needed:

In my own project the issue can be repruces by 

invocation of ./ga inside the main folder of 

https://github.com/MobMonRob/DSL4GeometricAlgebra

Clone the repro, build it and than execute ./ga inside the main folder.

The problem is a strange blocker for me to use jzy3d. I am wondering that nobody else has reported the problem. If I understand correctly since Java9 the listed keywords are not allowed to use in the jar file names.

best regards
Oliver

**Comment by orat** [comment]
I think here are some additional helpful hints

http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by jzy3d** [comment]
Hi,
I've worked with OpenJDK 9, 14, 17 (and maybe more) without such issue in the past. 
Could a maven plugin renaming artifacts help to resolve your issue?

**Comment by orat** [comment]
Renaming the artifacts should help, but I have not yet tested it - I have first to learn how to do it with Maven:-(
With OpenJDK also for me I can not reproduce the problem. I have it with graalVM (essential for our DSL4GeometricAlgebra project) only, e.g. graalvm-community-openjdk-22.0.2+9.1, graalvm-ce-java17-22.3.2

**Comment by orat** [comment]
I want to give an all-clear-signal to this issue. The error message is misleading and the error seams to have its origin in that the jogl implementation jzy3d is based on includes some classes which are also included in an other package which is included from my code. So not the naming of the package itself produces the problem but some specific classes inside the package.

**Comment by jzy3d** [comment]
Thanks for sharing your findings.
