### ISSUE TITLE
Provide source and javadoc jars on deployment

### ISSUE THREAD

**Issue by AxeTheAxe** [jzy3d/jzy3d-api#41]
It would be very helpful for development time to attach source and javadoc jars to the binary libs in ones IDE. Providing such jars is very easy using Maven with the help of the maven-source-plugin resp. maven-javadoc-plugin.

**Comment by jzy3d** [comment]
https://github.com/jzy3d/jzy3d-api/commit/2378853797a56278825979898d16bbd98dd91ef9
