### ISSUE TITLE
Why do I have a blank canvas when trying to render using jzy3d v0.9.1 on Ubuntu 15.10?

### ISSUE THREAD

**Issue by jeemar** [jzy3d/jzy3d-api#51]
I posted this issue on [stackoverflow](http://stackoverflow.com/questions/34010960/why-do-i-have-a-blank-canvas-when-trying-to-render-using-jzy3d-v0-9-1-on-ubuntu). The trouble is I'm not able to run `jzy3d-0.9.1` on Ubuntu 15.10 or 12.04.

I get this error, when the running the sample code:

> Info: Nativewindow X11 Error: 2 - BadValue (integer parameter out of range for operation), dpy 0x7feed88b0d10, id 0, # 194: 12:0 X_ConfigureWindow

and this when I close the test dialog, 

> X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 3/3, reusable (open, marked uncloseable): 0, pending (open in creation order): 3)
> X11Util: Open X11 Display Connections: 3
> X11Util: Open[0]: NamedX11Display[:0, 0x7fd5acb420e0, refCount 1, unCloseable false]
> X11Util: Open[1]: NamedX11Display[:0, 0x7fd548003250, refCount 1, unCloseable false]
> X11Util: Open[2]: NamedX11Display[:0, 0x7fd54800f460, refCount 1, unCloseable false]

**Comment by julien-diener** [comment]
FYI: I just run the surface demo on ubuntu 15.10 (unity). 
There were a strange bug when moving  the windows on my second screen, but at start it worked

**Comment by hlfernandez** [comment]
I am experiencing the same problem on a fresh install of Kubuntu 14.04 LTS. Have you fixed it?.

Thanks.

**Comment by jeemar** [comment]
@hlfernandez I have not. I moved to Ubuntu 16.04 and when I get the chance to reproduce the problem, I'll let you know if it's present in 16.04.

**Comment by jzy3d** [comment]
I presume this might be fixed since 2016! We are now at Jzy3d 2.0, using JOGL 2.3.2. Maybe this fixed the problem? You may try Jzy3d 1.0.3, 1.0.2 as well.

Please reopen the issue if not.
