### ISSUE TITLE
Character "€" does not appear in axis labels

### ISSUE THREAD

**Issue by jzy3d** [jzy3d/jzy3d-api#55]
chart.getAxeLayout().setYAxeLabel( "Amount (€)" );

Will appear like : "Amount ()"

**Comment by xkok** [comment]
Chinese Character like "中" is also not appear.

**Comment by jzy3d** [comment]
You have to implement a TextRenderer supporting this character. The default one is limited. You might wish to use an existing JOGL text renderers instead. 

A JOGL text renderer is wrapped in Jzy3d : although it does not work it can be starting point for you. Please share your work if you make it work :)

To replace the current AxeBox text renderer, you have to call :
 
((AxeBox)chart.getView().getAxe()).setTextRenderer(new MyTextRenderer());

**Comment by jzy3d** [comment]
You may use EmulGL charts which has a more flexible text renderer based on Graphics2D.drawString instead of OpenGL text rendering.

Since version 2.0.0
