### ISSUE TITLE
Setting output folder for screenshot

### ISSUE THREAD

**Issue by zhivko** [jzy3d/jzy3d-api#57]
Is there a way to set screenshot folder for AbstractAnalysis take screenshot functionality?

**Comment by martinpernollet** [comment]
See AWTChartComponentFactory.newScreenshotKeyController(...)

2016-05-05 16:26 GMT+02:00 zhivko <notifications@github.com>:

**Comment by zhivko** [comment]
OK I see i can change it with:
			ChartComponentFactory.SCREENSHOT_FOLDER = folder;
but once AbstractAnalysis is instantiated, I see no way how I can to change that property?

AbstractAnalysis.getChart().getControllers() doesn't hold any screenshot controller - only abstractcamera controllers, so is there no way to change screenshot folder once AbstractAnalysis is created?
