### ISSUE TITLE
jzy3d-swt.pom maven build error

### ISSUE THREAD

**Issue by alicanalbayrak** [jzy3d/jzy3d-api#58]
Hi,

It seems there is no **[org.eclipse.swt.gtk.linux.x86_64](http://mvnrepository.com/artifact/org.eclipse.swt.org.eclipse.swt.gtk.linux.x86_64.4.3.swt/org.eclipse.swt.gtk.linux.x86_64)** with version **4.2.1** according to [maven central repo](http://mvnrepository.com/artifact/org.eclipse.swt.org.eclipse.swt.gtk.linux.x86_64.4.3.swt/org.eclipse.swt.gtk.linux.x86_64). I changed it to version 4.3 and successfully builds.

FYI

**Comment by alicanalbayrak** [comment]
I just noticed following lines in jzy3d-swt.pom

```xml
<repositories>
	<repository>
		<id>swt-repo</id>
		<url>https://swt-repo.googlecode.com/svn/repo/</url>
	</repository>
</repositories>
```

But, still, [https://swt-repo.googlecode.com/svn/repo/](https://swt-repo.googlecode.com/svn/repo/) is dead right now. I do not know if its temporary situation or not ?

**Comment by alicanalbayrak** [comment]
I just noticed following lines in jzy3d-swt.pom

```xml
<repositories>
    <repository>
        <id>swt-repo</id>
        <url>https://swt-repo.googlecode.com/svn/repo/</url>
    </repository>
</repositories>
```
But, still, [https://swt-repo.googlecode.com/svn/repo/](https://swt-repo.googlecode.com/svn/repo/) is dead right now. I do not know if its temporary situation or not ?

Ps. Sorry I accidentally closed this issue. Reopened now.

**Comment by jzy3d** [comment]
I don't know either. Did you solve your problem?

**Comment by Yodeser** [comment]
Hello！Could you give me a demo about how to use JZY3D in SWT?
