### ISSUE TITLE
Chart2d with date as x values

### ISSUE THREAD

**Issue by lgas** [jzy3d/jzy3d-api#59]
Here are main() file and result to reproduce.

[chart2DwDate.txt](https://github.com/jzy3d/jzy3d-api/files/270036/chart2DwDate.txt)
![plottingresult](https://cloud.githubusercontent.com/assets/15610160/15353265/76d1906c-1ce8-11e6-9988-003574cc4b3a.png)

**Comment by lgas** [comment]
Hi,
Are there any news ?

**Comment by jzy3d** [comment]
Sorry, ultra busy for the moment. Can you set boundingbox manually using your min/max values on x and y?

BoundingBox3d b = chart.getView().getBounds().clone();
b.setXmin(...)
chart.getView().setBounds(b)

**Comment by jzy3d** [comment]
No news good news, I presume the suggested fix worked. Please re-open if not.
