### ISSUE TITLE
Maven repository down

### ISSUE THREAD

**Issue by hlfernandez** [jzy3d/jzy3d-api#61]
Dear jzy3d team,

the maven repository seems (http://maven.jzy3d.org/) to be down since two weeks ago. Is this a temporary problem?

Thank you very much for this nice project.

Regards.

**Comment by martinpernollet** [comment]
I can open URL without problem. Any stacktrace?

**Comment by hlfernandez** [comment]
Dear Martin,

thank you for your fast response. I have tested it using other network and it works, It must be a problem with our office's network.

Regards.
