### ISSUE TITLE
Wrong axes layout in 2D

### ISSUE THREAD

**Issue by hlfernandez** [jzy3d/jzy3d-api#62]
Dear jzy3D team,

I have observed the following issue: when the view is in "2D mode" (both using ViewPositionMode.FREE or ViewPositionMode.TOP), axes layout is wrong since labels are overlapped within axes and chart. You can see this effect in the following image:
![2d-wrong-axes](https://cloud.githubusercontent.com/assets/3440230/15888858/f3b735ce-2d68-11e6-942e-0492d21349ee.png)

However, as you can see in the following two images, when the view is in "3D mode" (even when it is very close to the "2D/Top" view), labels are correctly displayed without being overlapped.

![3d-right-axes-2](https://cloud.githubusercontent.com/assets/3440230/15888859/f3ba17d0-2d68-11e6-95e0-417b84b3c4ee.png)
![3d-right-axes](https://cloud.githubusercontent.com/assets/3440230/15888860/f3bf19f6-2d68-11e6-817a-f81356fd64e6.png)

Is there any way to fix it? Can you consider fixing this issue in jzy3d?

Thank you very much for your support.

Regards.

**Comment by martinpernollet** [comment]
Use Chart2d with Chart2dComponentFactory.

2016-06-08 11:09 GMT+02:00 Hugo <notifications@github.com>:

**Comment by hlfernandez** [comment]
Dear Martin,

thank you very much. I have tried it and it looks much better using Chart2d with Chart2dComponentFactory.
![2d-1](https://cloud.githubusercontent.com/assets/3440230/15897817/40f4e7fa-2d96-11e6-9df3-c653a1a6ff22.png)
![2d-2](https://cloud.githubusercontent.com/assets/3440230/15897887/76cae6ea-2d96-11e6-8ab1-b9a23c448536.png)
It would look perfect if the X axis tick lines were not overlapping X axis labels, but it looks much better now.

Thank you very much for your support.

Regards.

**Comment by hlfernandez** [comment]
Dear Martin,

I have detected an issue with `Chart2d`: it does not respect the image proportions even when `setSquared(false)` is used.

Here is the result obtained using `AWTChartComponentFactory` and `Chart`:
![chart3d](https://cloud.githubusercontent.com/assets/3440230/15976054/df7c05be-2f50-11e6-9495-592b710e001e.png)

And here is the wrong result obtained using `Chart2dComponentFactory` and `Chart2d`:
![chart2d](https://cloud.githubusercontent.com/assets/3440230/15976055/df7c0bae-2f50-11e6-842b-20f0cf2af6f2.png)

In both cases I invoke `chart.getView().setSquared(false)` to.

Is there a way to fix this issue? 

Thank you very much.

Regards.

**Comment by hlfernandez** [comment]
I have just seen that class `View2d` (the one used by `Chart2d`) overrides `computeSceneScaling()` so that it always return `squarify()`. I think that this must be the reason why `setSquared(false)` does not have effect on `Chart2d`. 

Do you know any way of having a squared `Chart2d`?

Thank you very much.

**Comment by martinpernollet** [comment]
I confirm it is a non desired behavior.
You might try removing the override, or override the override with
overriden impl or wait for a fix but I can t promise any deadline

**Comment by hlfernandez** [comment]
Thank you very much for your suggestion. Indeed, removing the override is precisely what I tried. This way, the `setSquared(false)` works and the image is rendered respecting its real dimensions. Finally, to obtain a slightly better layout of the axes I have overriden the `drawAxisTicks` and `layoutHorizontal` in `AxeBox2d` class.

It would be nice if you can fix this in future versions.

Best regards,

Hugo.

**Comment by martinpernollet** [comment]
Could you kindly perform a pull request so that your improvements will be
merge in future version?

Thank you!

2016-06-14 18:06 GMT+02:00 Hugo <notifications@github.com>:

**Comment by hlfernandez** [comment]
Ok, I will perform a pull request when I have these changes totally tested in my application.

Thank you for your support too.

**Comment by jzy3d** [comment]
Version 2.1.0 now provides much better 2D charts! See the tutorial chart2d package.
