### ISSUE TITLE
Chinese character support

### ISSUE THREAD

**Issue by Yodeser** [jzy3d/jzy3d-api#72]
As we all know , if I want to edit the name of axis , I must use the follow codes
`chart.getAxeLayout().setXAxeLabel("");
chart.getAxeLayout().setYAxeLabel("");
chart.getAxeLayout().setZAxeLabel("");`
But it didn't work when I use its in Chinese , just here so：
`chart.getAxeLayout().setXAxeLabel("X轴");
`

Could you tell me any method to resolve it?
Thanks for you help!

**Comment by jzy3d** [comment]
Also discussed in https://github.com/jzy3d/jzy3d-api/issues/55

Not supported yet.

**Comment by jzy3d** [comment]
As of version 2.0 you may use EmulGL charts that have a more flexible text renderer based on JVM Graphics2D instead of OpenGL.

See SurfaceDemoEmulGL in tutorials.
