### ISSUE TITLE
NewtCanvasSWT option 

### ISSUE THREAD

**Issue by jacobfilik** [jzy3d/jzy3d-api#77]
Dear jzy3d developers,

We are investigating different 3d plotting technologies to use in our application [DAWN](http://dawnsci.org/) to replace our current jreality and javafx code.

Jzy3d looks like a good candidate but we use SWT and have had issue in the past with the SWT_AWT bridge causing deadlock on some older versions linux.

I noticed that for AWT you can use the JOGL newt canvas, for which an SWT version also exists (which I assume would allow us to run in SWT without the bridge).

I am happy to investigate this, if I can get it working nicely are you likely accept a pull request for this feature?

Kind regards,

Jacob

**Comment by jzy3d** [comment]
Sure we will merge your work!
Thank you for participating.
