### ISSUE TITLE
ply visualization?

### ISSUE THREAD

**Issue by arianaa30** [jzy3d/jzy3d-api#84]
I just came into your library. Does it support reading a XYZRGB .ply file and visualize it?
I need zoom in, zoom out, rotation features. The files can be dense like 1M points.

**Comment by jzy3d** [comment]
It can read Ply files (https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-api/src/api/org/jzy3d/io/ply/Ply.java) but it only load XYZ. 

You should enhance the reader to let it load Point instance (a point is made of a Coord3d and a Color)

**Comment by arianaa30** [comment]
Right-  `org.smurn.jply.ElementReader` will give u the color and we need to convert it to Point.
What is ScatterVBO? Where and how should be use it?

**Comment by jzy3d** [comment]
ScatterVBO is a jzy3d class allowing fast rendering of denser scatters. It is more efficient than the standard Scatter class.

Read about Vertex Buffer Object to better understand why it is faster. 

See also the Jzy3d project named BigPicture.

**Comment by martinpernollet** [comment]
Did you finally implemented loading colors from PLY files?
If so, I would be interested by the code and a sample PLY file containing
color informations.
Regards

2017-07-23 19:53 GMT+02:00 jzy3d <notifications@github.com>:
