### ISSUE TITLE
Other options to setSquared

### ISSUE THREAD

**Issue by jacobfilik** [jzy3d/jzy3d-api#87]
A lot of the data I want to plot has common axes in X and Y (say mm) and an arbitrary Z (intensity for example).

Plotting this data without setting the view as " not squared" sets the aspect ratio as if all the axes have the same unit (which makes the data look funny), where as squaring the view loses the sensible aspect ratio of X and Y.

Ideally I would like a mode on the view that keeps the aspect ratio of X and Y but uses an arbitrary Z (that makes XZ or YZ square for example).

Is this possible and have I just missed it?

If not I am happy to look at implementing it, but I would probably like a bit of guidance on how best to do it (an enum with values of squared, ratio_all, ratio_xy, or add another boolean to setSquared to not square X and Y).

**Comment by martinpernollet** [comment]
You might use SpaceTransform for flexibility. I use it to apply log
transforms to drawables and axes. It can also be applied to the view.

SpaceTransform is used to transform th geometry of a primitive (coord3d)
before being used to call OpenGL functions.

Hope this helps.



Le mar. 10 oct. 2017 à 09:54, Jacob Filik <notifications@github.com> a
écrit :

**Comment by martinpernollet** [comment]
But it is probably easier to edit the squarify method so that it can be
given an arbitrary Squarifier functor to perform the scaling you wish.

**Comment by jacobfilik** [comment]
Ah, I didn't think of a visitor-type approach, I will have a look at how that might work.

I'm just having a quick go at rendering a volume into a jzy3d chart, I will try and implement something on this when I have finished trying that.

**Comment by jacobfilik** [comment]
Feature added in #88
