### ISSUE TITLE
Sourc code for jzy3d-guide?

### ISSUE THREAD

**Issue by ThomasDaheim** [jzy3d/jzy3d-api#90]
I was looking for the source code for jzy3d-guide but couldn't find it. It would be a good addition to the documentation to see how all types of diagrams are created.

I was especially trying to find other usage examples for Spline3D and HeightMap but couldn't find any...

**Comment by martinpernollet** [comment]
Hi,

You can get it by buying the developer guide which comes with code examples
that produced the gallery images :

http://jzy3d.org/guide.php

2018-01-20 22:05 GMT+01:00 Thomas Feuster <notifications@github.com>:

**Comment by ThomasDaheim** [comment]
Thanks for the info.

Need to see if thats something I would invest for my small pet project that is also freely available on github...
