### ISSUE TITLE
trying to open jzy3d class from java class.

### ISSUE THREAD

**Issue by ghost** [jzy3d/jzy3d-api#91]
Hi,

      I am trying to open jzy3d class from java class,but its giving me an error.Can anyone help me on this 
error:  org.jzy3d.plot3d.rendering.canvas.VoidCanvas cannot be cast to javax.swing.JComponent

**Comment by elijahjude** [comment]
thank you for AWTChartComponentFactory. when i run this the plot,the plot is static and not rotation in 3d.

`import org.jzy3d.chart.Chart;
import org.jzy3d.chart.Settings;
import org.jzy3d.chart.factories.AWTChartComponentFactory;
import org.jzy3d.chart.factories.IChartComponentFactory;
import org.jzy3d.colors.Color;
import org.jzy3d.colors.ColorMapper;
import org.jzy3d.colors.colormaps.ColorMapRainbow;
import org.jzy3d.maths.Range;
import org.jzy3d.plot3d.builder.Builder;
import org.jzy3d.plot3d.builder.Mapper;
import org.jzy3d.plot3d.builder.concrete.OrthonormalGrid;
import org.jzy3d.plot3d.primitives.Shape;
import org.jzy3d.plot3d.rendering.canvas.Quality;

import javax.swing.*;
import java.awt.*;

public class SurfaceViewerFrame extends JFrame {

    public SurfaceViewerFrame() {
        setResizable(false);

        Mapper mapper = new Mapper() {
            public double f(double x, double y) {
                return x * Math.sin(x * y);
            }
        };
        // Define range and precision for the function to plot
        Range range = new Range(-300, 300);
        int steps = 80;

        // Create the object to represent the function over the given range.
        final Shape surface = Builder.buildOrthonormal(new OrthonormalGrid(range, steps, range, steps), mapper);
        surface.setColorMapper(new ColorMapper(new ColorMapRainbow(), surface.getBounds().getZmin(), surface.getBounds().getZmax(), new Color(1, 1, 1, .5f)));
        surface.setFaceDisplayed(true);
        surface.setWireframeDisplayed(false);

        // Create a chart
        Chart chart = AWTChartComponentFactory.chart(Quality.Advanced, IChartComponentFactory.Toolkit.swing);
        chart.getScene().getGraph().add(surface);
        //chart.addController(new CameraKeyController());

        JPanel panel=new JPanel();
       // panel.add(title, сс.xy(1, 1));
        Component canvas = (Component) chart.getCanvas();
        add(canvas);
        //add(panel);
        setSize(320, 370);
        setVisible(true);
    }
    
    public static void main(String[] args)
    {
        SurfaceViewerFrame ref = new SurfaceViewerFrame();
    }
}`

this is my code martin.any help ?

**Comment by martinpernollet** [comment]
The developer guide will help you!

http://jzy3d.org/guide.php


2018-02-21 12:56 GMT+01:00 elijahjude <notifications@github.com>:

**Comment by elijahjude** [comment]
I already have them martin.there is no example saying how we can call jzy3d class from java class nor how to use jframe.

**Comment by martinpernollet** [comment]
There 50 code examples!

Contact martin @ jzy3d.org with the email you used to buy the guide to have
support on this point.

2018-02-22 13:58 GMT+01:00 elijahjude <notifications@github.com>:
