### ISSUE TITLE
Zooming outside the boundaries of the window

### ISSUE THREAD

**Issue by spadino** [jzy3d/jzy3d-api#93]
Hi! I'd like to know how can I zoom a chart outside the boundaries of the window. I want to closely inspect a scatter plot, but I only can zoom until it reach the boundaries, than it stops...

**Comment by DavenH** [comment]
I am not even sure how to zoom in any respect, except resizing the window. Mouse wheel expands the Z-dimension, which isn't a big help. Cannot see how to programmatically enlarge the scatterplot without it being downsized back to the window bounding box.

**Comment by jzy3d** [comment]
Hi, as of Jzy3d 2.0 (January 2021), on may use chart.getView().setCameraRenderingSphereRadiusFactor( x< 1 ) will produce a simple zoom effect but you won't be able to pan the zoomed chart. Is this something required for your use case?

* A value of 1 allows having an AxisBox with corners touching the top/bottom part of the canvas.
* A value greater than 1 makes the rendering sphere bigger, hence the AxisBox appears smaller.

Please reopen the issue with more requirements if this is not satisfying.
