### ISSUE TITLE
Ranges are floats

### ISSUE THREAD

**Issue by shortwavedave** [jzy3d/jzy3d-api#95]
Why are the ranges floats and not doubles? Having some problems with geographic data that is pretty dense

**Comment by jzy3d** [comment]
Actually the complete API is working with float for rendering.

There is however a dedicated Coord3D (not Coord3d) to store data as double that could be used to create drawable primitives to be rendered with double, but there is lot of work to generalize the complete API to work with double.

Could you describe your rendering use case ?
