### ISSUE TITLE
[Native] SurfaceDemo show only only black screen with canvastype = awt / Debian 4.9

### ISSUE THREAD

**Issue by laeubi** [jzy3d/jzy3d-api#99]
Maybe thsi is related to #94 but I don't see any exceptions. If I run the surface-demo with "awt" (others demos work well) the image is visible for a second and then the window stays black, if I switch to "newt" everything seem to work.

**Comment by laeubi** [comment]
The same applies to the "WorldMapDemo"

**Comment by jzy3d** [comment]
Weird. Which environment (OS, GPU, JVM)?

**Comment by laeubi** [comment]
OS: Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
JVM: Java(TM) SE Runtime Environment (build 1.8.0_144-b01), Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
GPU: FirePro 2460

Let me know if you need further information.

**Comment by laeubi** [comment]
If I press "s" on the demo the following exception occurs

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.jogamp.opengl.util.texture.TextureIO$PNGTextureWriter.write(TextureIO.java:1384)
	at com.jogamp.opengl.util.texture.TextureIO.write(TextureIO.java:686)
	at org.jzy3d.chart.controllers.keyboard.screenshot.AbstractScreenshotKeyController.screenshot(AbstractScreenshotKeyController.java:45)
	at org.jzy3d.chart.controllers.keyboard.screenshot.AWTScreenshotKeyController.keyTyped(AWTScreenshotKeyController.java:23)
	at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:240)
	at java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:239)
```

Maybe this helps to find out whats going wrong?

**Comment by laeubi** [comment]
Any further information required?

**Comment by jzy3d** [comment]
Hi, I presume this should still happen as JOGL dependencies have not changed.
In case it still happen, you may try EmulGL charts instead since it will use an alternative gl renderer.

**Comment by laeubi** [comment]
@jzy3d is EmulGL an alternative render for jz3d or do you suggest EmulGL as an alternative charting to jz3d itself?

**Comment by jzy3d** [comment]
Hi, it is an alternative renderer in Jzy3d. See description and links to the demo programs here : https://github.com/jzy3d/jzy3d-api/tree/master/jzy3d-emul-gl

**Comment by laeubi** [comment]
wow that's amazing. I'll try this out have you ever tired this in combination with **SWT** (Eclipse) already? Removing the need for native libs will greatly reduce the hassle to integrate this, and sadly jogl seems to be a dead-end as for now (no new public releases for months).

**Comment by jzy3d** [comment]
Hi, I haven't tested with SWT already but you may do it in one line with `SWT_AWT_Bridge.adapt(...)`
There is an example of this in class `FrameSWTBridge`.

**Comment by jzy3d** [comment]
By the way, JOGL is not dead. It goes slowly however. A candidate release version for 2.4 has recently been set online. 

However they [did not make it accessible via Maven](http://forum.jogamp.org/Maven-repo-to-get-2-4-0-rc-td4041046.html) so we have to do it by ourself :/

**Comment by laeubi** [comment]
> By the way, JOGL is not dead. It goes slowly however.

But that's the problem, if a bugfix takes months to be released it makes it simply 'dead' for any project bitten by that bug.

> I haven't tested with SWT already but you may do it in one line with `SWT_AWT_Bridge.adapt(...)`

My aim is to really avoid SWT<->AWT bridge as it is sometimes causes problems in SWT. As the rendering is now pure java I wonder if it is possible to have a "native" SWT impl by just providing some kind of surface EmulGL can draw to?

**Comment by jzy3d** [comment]
Yes this is not complicated. 

The java [GL implementation renders in a BufferedImage](https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-jGL/src/main/java/jgl/GL.java#L236). If drawing in a BufferedImage is acceptable for an SWT application, then we simply need to adapt the EmulGLCanvas/GLCanvas hierarchy to inherit an SWT canvas could handle painting the rendered image AND getting mouse/keyboard events. 

If drawing in BufferedImage is not acceptable, one may think of overriding this GL.glFLush() to copy the pixels in an SWT image.
 
You may look at [EmulGLCanvas](https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-emul-gl/src/main/java/org/jzy3d/plot3d/rendering/canvas/EmulGLCanvas.java#L183) to understand how the GL image is rendered and then swapped in canvas.

**Comment by laeubi** [comment]
>  If drawing in a BufferedImage is acceptable for an SWT application

That is possible, I have used such an approach already, but

> one may think of overriding this GL.glFLush() to copy the pixels in an SWT image

this sound better than copy everything to BufferedImage, then copy it over to SWT image, then do the paint

> SWT canvas could handle painting the rendered image AND getting mouse/keyboard events

yes that would be the best integration i think. As SWT is very strict in event-handling/threading this might be even less hassle than AWT integration?

> You may look at [EmulGLCanvas](https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-emul-gl/src/main/java/org/jzy3d/plot3d/rendering/canvas/EmulGLCanvas.java#L183) to understand how the GL image is rendered and then swapped in canvas.

I hope to get some time the next days to setup an example project, get all the dependencies and so on. Is there a snapshot-repro that one should use for such edge-of-devlopment purposes?

**Comment by laeubi** [comment]
@jzy3d Maybe it would be even a better choice to integrate EmuGL with the  [SWT OpenGL API](https://www.eclipse.org/swt/opengl/) what do you think?

**Comment by jzy3d** [comment]
Similar to your suggestion I first thought about integrating jGL inside JOGL. I found easier to make the integration in Jzy3d. The glue between Jzy3d and each OpenGL library is in IPainter interface, implemented by EmulGLPainter (for jGL) on one side and by NativeDesktopPainter (for JOGL) on the other side.

Incorporating the SWT GLCanvas in Jzy3d would bring LWJGL, gljava, etc to the classpath. I found that LWJGL is not more stable/working than JOGL (at least on my mac), and the community is not bigger nor active than JOGL. Moreover, the best integration of native rendering in SWT is - to my knowledge - the [CanvasNewtSwt](https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-native-jogl-swt/src/main/java/org/jzy3d/chart/factories/CanvasNewtSWT.java) that @jacobfilik introduced in Jzy3d. It makes use of Newt and avoid the AWT/SWT bridge I proposed.

**Comment by jzy3d** [comment]
Sorry for the snapshot repo, if you mean Maven then yes, I deploy intermediate snapshots [here](https://maven.jzy3d.org/snapshots/).

On git I do feature branch and merge/pull request.

**Comment by laeubi** [comment]
> Incorporating the SWT GLCanvas in Jzy3d would bring LWJGL, gljava, etc to the classpath.

I more though to make jGL/EmulGL available as (swt) GLCanvas (there is also a class named GLCanvas in jogl so don't be confused!) and the use that "Jzy3DGLCanvas" for rendering of Jz3d charts as opposed to extend the "plain" swt Canvas!

**Comment by laeubi** [comment]
> You may look at [EmulGLCanvas](https://github.com/jzy3d/jzy3d-api/blob/master/jzy3d-emul-gl/src/main/java/org/jzy3d/plot3d/rendering/canvas/EmulGLCanvas.java#L183) to understand how the GL image is rendered and then swapped in canvas.

sorry to ask again just to be sure:
EmulGL is the bridge between jzy3d and jGL using AWT? So when I'd like to have a more "native" SWT impl I would also use jGL and not try to adjust EmulGL correct?

**Comment by jzy3d** [comment]
No problem at all. Do not hesitate to ask more advices if needed.

Short answer is : yes, you want to work on jGL. EmulGL is the integration of jGL in jzy3d. 

Other suggestions
- rename jzy3d-jGL to jzy3d-jGL-awt and create jzy3d-jGL-swt depending on the first one. I noticed that adding SWT dependencies in an AWT project prevent to open the AWT apps on my computer. Your attempt may rely mainly on 
- [ ] overriding GL.glFlush() and adding a GL.glXSwapBuffer( ... ) relevant for SWT. 
- [ ] overriding GLUT.processComponentEvent to deal with SWT events
- you may use the [GL Red Book example](https://github.com/jzy3d/jzy3d-api/tree/master/jzy3d-jGL/src/main/java/examples/apps) provided with jGL to make simple tests. 
- soon or later you will wish to use Jzy3d to add content for richer charts. Then you will need to create EmulGLCanvasSWT that will be a mix of CanvasSWT and EmulGLCanvas.

**Comment by laeubi** [comment]
> I noticed that adding SWT dependencies in an AWT project prevent to open the AWT apps on my computer.

As SWT also uses native libs there are chances for collisions here, that wha the SWT project generally avoids (if possible) using AWT but there is a also AWT_SWT bridge and it seems jGL uses much of AWTs rendering so it might be hard to exchange completely.

> rename jzy3d-jGL to jzy3d-jGL-awt and create jzy3d-jGL-swt depending on the first one

I don't know enough about the jGL lib but maybe it would be possible to split the AWT independent part and later have:

- jzy3d-jGL-core
- jzy3d-jGL-awt
- jzy3d-jGL-swt
- jzy3d-jGL-.... (what ever will be cool in the future)

GLCanvas then might be an abstract class with glFlush() the responsibility of the actual AWTGLCanvas / SWTGLCanvas/ ...GLCanvas and similar to other classes that might be relevant?

That would prevent duplication and would make it clear what integrator to other UI frameworks need to actually do.

**Comment by jzy3d** [comment]
I agree with the module layout you propose. jGL core would contain only an abstract GL and AWT/SWT would implement the missing parts (glFlush/SwapBuffer/etc). I also agree on canvas naming : all component in Jzy3d are named [WT]Component but not canvas that are named Canvas[WT], so keep your naming proposal.

I also want to keep EmulGL separated from jGL to let anybody use jGL without Jzy3d.

You are right that the common point is the colorbuffer copy. All text and sprite addition based on AWT were added by me as a simple workaround to the lack of text/sprite support in jGL (despite textures are possible but I did not explore yet).

**Comment by jzy3d** [comment]
Side question : do you know a good document explaining what are the differences between AWT and SWT threading model?I know general stuff but I would be happy to have a better understanding of what happens inside in terms of threads, concurrency, etc.

**Comment by jzy3d** [comment]
Let's continue discussion `https://github.com/jzy3d/jzy3d-api/discussions/166`!

**Comment by jzy3d** [comment]
Hi,
After recently publishing 2.0 release version on maven repo, I started `2.0.1-SNAPSHOT` by bumping JOGL to a more recent version (2.4.0 RC produced in 2021), which may potentially come with a fix for your problem. 
You may give a try based on the updated tutorials [here](https://github.com/jzy3d/jzy3d-api/tree/master/jzy3d-tutorials). Thanks in advance for your feedback!
